export default [
  {
    id: 1,
    name: "Name 1",
    date: "Date 1",
    venue: "Place 1",
    description: "Description 1",
    teams: "Team 1 and team 2",
    prices: "10$",
  },
  {
    id: 2,
    name: "Name 2",
    date: "Date 2",
    venue: "Place 2",
    description: "Description 2",
    teams: "Team 1 and team 3",
    prices: "15$",
  },
  {
    id: 3,
    name: "Name 3",
    date: "Date 3",
    venue: "Place 3",
    description: "Description 3",
    teams: "Team 4 and team 2",
    prices: "20$",
  },
  {
    id: 4,
    name: "Name 4",
    date: "Date 4",
    venue: "Place 4",
    description: "Description 4",
    teams: "Team 1 and team 5",
    prices: "50$",
  },
  {
    id: 5,
    name: "Name 5",
    date: "Date 5",
    venue: "Place 5",
    description: "Description 5",
    teams: "Team 3 and team 2",
    prices: "30$",
  },
];
